repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.2
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: local
  hooks:
    - id: hadolint
      name: Lint Dockerfiles
      description: Runs hadolint to lint Dockerfiles
      language: system 
      types: ["dockerfile"]
      entry: hadolint
