name: CI
on: push


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ruff (python)
        uses: astral-sh/ruff-action@v3
      - name: Lint using ruff (python)
        run: ruff check
      - name: Format using ruff (python)
        run: ruff format

      - name: Lint using hadolint (docker)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run tests
        run: pytest tests.py -v

